apiDebug: true
restVersion: 6
timeout: 120000
dappPath: ./dapp
libPath: ./blockapps-sol
apiUrl: /api/v1
deployFilename: ./config/localhost.deploy.yaml

nodes:
- id: 0
  stratoUrl: 'http://localhost:8080/strato-api'
  blocUrl: 'http://localhost:8080/bloc/v2.2'
  searchUrl: 'http://localhost:8080/cirrus'

oauth:
  appTokenCookieName: "tt_session"
  scope: 'email openid'
  appTokenCookieMaxAge: 7776000000 # 90 days: 90 * 24 * 60 * 60 * 1000
  stratoUrl: "http://localhost:8080"
  clientId: "tt-localhost"
  clientSecret: "10352ea6-f286-47cf-936c-2cb7ce6c1c39"
  openIdDiscoveryUrl: "https://keycloak.blockapps.net/auth/realms/track-and-trace/.well-known/openid-configuration"
  redirectUri: "http://localhost/api/v1/authentication/callback"
  logoutRedirectUri: "http://localhost" # url to redirect after OAuth logout (e.g. app's login screen)
